# Generated by Django 6.0.7 on 2026-07-28 03:00

from django.db import migrations

TIPOS_DOCUMENTO = ['Cédula de ciudadanía', 'Tarjeta de identidad', 'Cédula de extranjería']
GRUPOS = ['Administrador', 'Medico', 'Paciente']


def crear_catalogos_y_grupos(apps, schema_editor):
    TipoDocumento = apps.get_model('usuarios', 'TipoDocumento')
    Group = apps.get_model('auth', 'Group')

    for nombre in TIPOS_DOCUMENTO:
        TipoDocumento.objects.get_or_create(nombre=nombre)

    for nombre in GRUPOS:
        Group.objects.get_or_create(name=nombre)


def eliminar_catalogos_y_grupos(apps, schema_editor):
    TipoDocumento = apps.get_model('usuarios', 'TipoDocumento')
    Group = apps.get_model('auth', 'Group')

    TipoDocumento.objects.filter(nombre__in=TIPOS_DOCUMENTO).delete()
    Group.objects.filter(name__in=GRUPOS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(crear_catalogos_y_grupos, eliminar_catalogos_y_grupos),
    ]
