# Generated by Django 6.0.7 on 2026-08-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0006_tipodocumento_codigo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usuario',
            name='uq_usuario_tipo_numero_documento',
        ),
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(fields=('numero_documento',), name='uq_usuario_numero_documento'),
        ),
    ]
