# Generated by Django 6.0.7 on 2026-08-19 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_usuario_uq_usuario_tipo_numero_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioUsuarioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=50)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('realizado_por', models.ForeignKey(help_text='Nulo cuando el cambio lo hizo un proceso automático, no una persona. Cuando alguien edita sus propios datos, es esa misma persona, nunca nulo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de cambio de usuario',
                'verbose_name_plural': 'Registros de cambio de usuario',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
