# Generated by Django 6.0.7 on 2026-07-28 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('usuarios', '0004_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariomedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='usuarios.medico'),
        ),
        migrations.AddConstraint(
            model_name='horariomedico',
            constraint=models.UniqueConstraint(fields=('medico', 'dia_semana', 'hora_inicio'), name='uq_horario_medico_dia_hora_inicio'),
        ),
        migrations.AddConstraint(
            model_name='horariomedico',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='ck_horario_medico_fin_mayor_inicio'),
        ),
    ]
