# Generated by Django 6.0.7 on 2026-07-28 22:39

from django.db import migrations

ESPECIALIDADES = [
    ('Medicina general', 20),
    ('Odontología', 40),
    ('Pediatría', 30),
]


def crear_especialidades(apps, schema_editor):
    Especialidad = apps.get_model('citas', 'Especialidad')
    for nombre, duracion in ESPECIALIDADES:
        Especialidad.objects.get_or_create(nombre=nombre, defaults={'duracion_cita_min': duracion})


def eliminar_especialidades(apps, schema_editor):
    Especialidad = apps.get_model('citas', 'Especialidad')
    Especialidad.objects.filter(nombre__in=[nombre for nombre, _ in ESPECIALIDADES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(crear_especialidades, eliminar_especialidades),
    ]
