# Generated by Django 6.0.7 on 2026-07-29 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_especialidades_iniciales'),
        ('usuarios', '0004_medico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de cita',
                'verbose_name_plural': 'Estados de cita',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo_consulta', models.CharField(blank=True, max_length=500)),
                ('comentario_medico', models.TextField(blank=True)),
                ('ocupa_slot', models.BooleanField(default=True, help_text='Derivado del estado: False cuando la cita está cancelada, para liberar el slot.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='usuarios.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas_paciente', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='citas.estadocita')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CitaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=20)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='citas.cita')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='citas.estadocita')),
            ],
            options={
                'verbose_name': 'Registro de cita',
                'verbose_name_plural': 'Registros de cita',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ExcepcionHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=120)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='usuarios.medico')),
            ],
            options={
                'verbose_name': 'Excepción de horario',
                'verbose_name_plural': 'Excepciones de horario',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['medico', 'fecha'], name='idx_cita_medico_fecha'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente', 'fecha'], name='idx_cita_paciente_fecha'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='ck_cita_fin_mayor_inicio'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('ocupa_slot', True)), fields=('medico', 'fecha', 'hora_inicio'), name='uq_cita_medico_slot_activo'),
        ),
    ]
