# Generated by Django 6.0.7 on 2026-07-29 23:18

from django.db import migrations

ESTADOS = ['confirmada', 'cancelada', 'atendida']


def crear_estados(apps, schema_editor):
    EstadoCita = apps.get_model('citas', 'EstadoCita')
    for nombre in ESTADOS:
        EstadoCita.objects.get_or_create(nombre=nombre)


def eliminar_estados(apps, schema_editor):
    EstadoCita = apps.get_model('citas', 'EstadoCita')
    EstadoCita.objects.filter(nombre__in=ESTADOS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_estadocita_cita_citalog_excepcionhorario_and_more'),
    ]

    operations = [
        migrations.RunPython(crear_estados, eliminar_estados),
    ]