# Generated by Django 6.0.7 on 2026-08-15 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_estado_no_atendida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='citalog',
            name='realizado_por',
            field=models.ForeignKey(help_text='Nulo cuando la transición la hizo un proceso automático (ver citas.services.cerrar_citas_vencidas), no una persona.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
